apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rstudio.fullname" . }}
  labels:
    {{- include "rstudio.labels" . | nindent 4 }}
  annotations:
    authproxy.stakater.com/enabled: "true"
    authproxy.stakater.com/source-service-name: {{ .Release.Name }}-service
    authproxy.stakater.com/upstream-url: "http://localhost:8787/"
    authproxy.stakater.com/client-id: {{ .Values.oidc.client_id }}
    authproxy.stakater.com/client-secret: {{ .Values.oidc.client_secret }}
    authproxy.stakater.com/listen: ":80"
    authproxy.stakater.com/discovery-url: {{ tpl .Values.oidc.discovery_url . }}
    authproxy.stakater.com/oauth-uri: "{{ .Values.ingress.access_path }}oauth"
    authproxy.stakater.com/gatekeeper-image: keycloak/keycloak-gatekeeper:7.0.0
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rstudio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rstudio.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rstudio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init-mounts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['sh', '-c', {{ include "rstudio.init-container-commands" . | squote }}]
          volumeMounts:
            {{- range $entry := .Values.mutableConfigs }}
            {{ if $entry -}}
            - name: rstudio-mutable-conf-files
              mountPath: /opt/configs/readonly/rstudio/{{$entry.subPath}}/{{ $entry.fileName }}
              subPath: {{ $entry.fileName }}
            {{- end -}}
            {{- end }}
            - name: rstudio-data
              mountPath: {{.Values.persistence.mountPath}}
              subPath: rstudio
            {{- if .Values.extraVolumeMounts }}
            {{- .Values.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DISABLE_AUTH
              value: "true"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8787
          readinessProbe:
            httpGet:
              path: /
              port: 8787
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $entry := .Values.mutableConfigs }}
            {{ if $entry -}}
            - name: rstudio-mutable-conf-files
              mountPath: /opt/configs/readonly/rstudio/{{$entry.subPath}}/{{ $entry.fileName }}
              subPath: {{ $entry.fileName }}
            {{- end -}}
            {{- end }}
            - name: rstudio-data
              mountPath: {{.Values.persistence.mountPath}}
              subPath: rstudio
            {{- if .Values.extraVolumeMounts }}
            {{- .Values.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: rstudio-mutable-conf-files
          {{- if .Values.useSecretConfigs }}
          secret:
            secretName: {{ template "rstudio.fullname" . }}-mutableconfigs
          {{- else }}
          configMap:
            name: {{ template "rstudio.fullname" . }}-mutableconfigs
          {{- end }}
        - name: rstudio-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "rstudio.pvcname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.extraVolumes }}
        {{- .Values.extraVolumes | toYaml | nindent 8 }}
        {{- end }}