apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rstudio.fullname" . }}
  labels:
    {{- include "rstudio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rstudio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rstudio.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rstudio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init-mounts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [
            'sh', '-c',
            '{{- if .Values.extraInitCommands -}}
             {{- tpl .Values.extraInitCommands $ | nindent 13 }};
             {{- end -}}
             {{ include "rstudio.init-container-commands" . }}']
          volumeMounts:
            {{- range $entry := .Values.mutableConfigs }}
            {{ if $entry -}}
            - name: rstudio-mutable-conf-files
              mountPath: /opt/configs/readonly/rstudio/{{$entry.subPath}}/{{ $entry.fileName }}
              subPath: {{ $entry.fileName }}
            {{- end -}}
            {{- end }}
            - name: rstudio-data
              mountPath: {{.Values.persistence.mountPath}}
            {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- .Values.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DISABLE_AUTH
              value: "true"
          ports:
            - name: http
              containerPort: 8787
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $entry := .Values.mutableConfigs }}
            {{ if $entry -}}
            - name: rstudio-mutable-conf-files
              mountPath: /opt/configs/readonly/rstudio/{{$entry.subPath}}/{{ $entry.fileName }}
              subPath: {{ $entry.fileName }}
            {{- end -}}
            {{- end }}
            - name: rstudio-data
              mountPath: {{.Values.persistence.mountPath}}
            {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- .Values.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: rstudio-mutable-conf-files
          {{- if .Values.useSecretConfigs }}
          secret:
            secretName: {{ template "rstudio.fullname" . }}-mutableconfigs
          {{- else }}
          configMap:
            name: {{ template "rstudio.fullname" . }}-mutableconfigs
          {{- end }}
        - name: rstudio-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "rstudio.pvcname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.extraVolumes }}
        {{- .Values.extraVolumes | toYaml | nindent 8 }}
        {{- end }}
