apiVersion: v1
metadata:
  name: {{ include "bioconductor.fullname" . }}-mutableconfigs
  labels:
    app.kubernetes.io/name: {{ include "bioconductor.name" . }}
    helm.sh/chart: {{ include "bioconductor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.useSecretConfigs }}
kind: Secret
type: Opaque
stringData:
{{- else }}
kind: ConfigMap
data:
{{- end }}
  {{- range $entry := .Values.mutableConfigs -}}
  {{- if $entry -}}
  {{- $entry.fileName | nindent 4 }}: |
    {{- $entry.contents | nindent 8 }}
  {{- end -}}
  {{- end -}}
