apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bioconductor.fullname" . }}
  labels:
    {{- include "bioconductor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bioconductor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bioconductor.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bioconductor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init-mounts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['sh', '-c', {{ include "bioconductor.init-container-commands" . | squote }}]
          volumeMounts:
            {{- range $entry := .Values.mutableConfigs }}
            {{ if $entry -}}
            - name: rstudio-mutable-conf-files
              mountPath: /opt/configs/readonly/rstudio/{{if $entry.subPath}}{{$entry.subPath}}/{{end}}{{ $entry.fileName }}
              subPath: {{ $entry.fileName }}
            {{- end -}}
            {{- end }}
            {{- if and .Values.libraries.persistence.enabled .Values.libraries.persistence.separateClaim.enabled }}
            - name: libraries
              mountPath: {{.Values.libraries.persistence.separateClaim.mountPath}}
            {{- end }}
            - name: rstudio-data
              mountPath: {{.Values.persistence.mountPath}}
              subPath: rstudio
            {{- if .Values.extraVolumeMounts }}
            {{- .Values.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.extraEnv }}
          env:
            {{- tpl (toYaml .Values.extraEnv) . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8787
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $entry := .Values.mutableConfigs }}
            {{ if $entry -}}
            - name: rstudio-mutable-conf-files
              mountPath: /opt/configs/readonly/rstudio/{{$entry.subPath}}/{{ $entry.fileName }}
              subPath: {{ $entry.fileName }}
            {{- end -}}
            {{- end }}
            - name: rstudio-data
              mountPath: {{.Values.persistence.mountPath}}
              subPath: rstudio
            {{- if .Values.extraVolumeMounts }}
            {{- .Values.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: rstudio-mutable-conf-files
          {{- if .Values.useSecretConfigs }}
          secret:
            secretName: {{ template "bioconductor.fullname" . }}-mutableconfigs
          {{- else }}
          configMap:
            name: {{ template "bioconductor.fullname" . }}-mutableconfigs
          {{- end }}
        - name: rstudio-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "bioconductor.pvcname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if and .Values.libraries.persistence.enabled .Values.libraries.persistence.separateClaim.enabled }}
        - name: libraries
          persistentVolumeClaim:
            claimName: {{ template "bioconductor.librariesClaimName" . }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- .Values.extraVolumes | toYaml | nindent 8 }}
        {{- end }}
