apiVersion: v1
kind: Service
metadata:
  name: {{ include "bioconductor.fullname" . }}
  labels:
    {{- include "bioconductor.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "bioconductor.selectorLabels" . | nindent 4 }}
